export const REQUEST_DESTINATIONS = 'REQUEST_DESTINATIONS'
export const GET_DESTINATIONS_FAILURE = 'GET_DESTINATIONS_FAILURE'
export const GET_DESTINATIONS_SUCCESS = 'GET_DESTINATIONS_SUCCESS'

export const REQUEST_REVIEWS = 'REQUEST_REVIEWS'
export const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
